CREATE TABLE IF NOT EXISTS Genres (
	ID SERIAL PRIMARY KEY,
	Name VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS Artists (
	ID SERIAL PRIMARY KEY,
	Name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Albums (
	ID SERIAL PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Year VARCHAR(4) NOT NULL
);

CREATE TABLE IF NOT EXISTS Tracks (
	ID SERIAL PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Length VARCHAR(10) NOT NULL,
	Album INTEGER REFERENCES Albums(ID)
);

CREATE TABLE IF NOT EXISTS Collections (
	ID SERIAL PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Year VARCHAR(4) NOT NULL
);

CREATE TABLE IF NOT EXISTS ArtistsGenres (
	GenreID INTEGER REFERENCES Genres(ID),
	ArtistID INTEGER REFERENCES Artists(ID),
	CONSTRAINT ga PRIMARY KEY (GenreID, ArtistID)
);

CREATE TABLE IF NOT EXISTS AlbumArtists (
	ArtistID INTEGER REFERENCES Artists(ID),
	AlbumID INTEGER REFERENCES Albums(ID),
	CONSTRAINT aa PRIMARY KEY (ArtistID, AlbumID)
);

CREATE TABLE IF NOT EXISTS CollectionTracks (
	TrackID INTEGER REFERENCES Tracks(ID),
	CollectionID INTEGER REFERENCES Collections(ID),
	CONSTRAINT tc PRIMARY KEY (TrackID, CollectionID)
);